// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAACHostel.Models;

#nullable disable

namespace SAACHostel.Migrations
{
    [DbContext(typeof(DataBaseModel))]
    [Migration("20211228195352_CorrectionDataBase_AddDateCreate_AddCountRoom")]
    partial class CorrectionDataBase_AddDateCreate_AddCountRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Faculty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<string>("Full_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Full_name_decan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone_decane")
                        .HasColumnType("TEXT");

                    b.Property<string>("Short_name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Facultys");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Hostel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count_Room")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<string>("Home_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("Hostels");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+LogEntry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_Ent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_Ext")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hostel_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Room_ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Student_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Hostel_ID")
                        .IsUnique();

                    b.HasIndex("Room_ID")
                        .IsUnique();

                    b.HasIndex("Student_ID")
                        .IsUnique();

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("LogEntrys");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Specialty", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<string>("Full_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Short_name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Specialtys");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faculty_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Full_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Home_address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pasport_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Short_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Specialty_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Faculty_ID")
                        .IsUnique();

                    b.HasIndex("Specialty_ID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("TEXT");

                    b.Property<string>("Full_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Home_address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pasport_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("BLOB");

                    b.Property<string>("Short_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Hostel", b =>
                {
                    b.HasOne("SAACHostel.Models.DataBaseModel+User", "User")
                        .WithOne("Hostel")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+Hostel", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+LogEntry", b =>
                {
                    b.HasOne("SAACHostel.Models.DataBaseModel+Hostel", "Hostel")
                        .WithOne("LogEntry")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+LogEntry", "Hostel_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAACHostel.Models.DataBaseModel+Room", "Room")
                        .WithOne("LogEntry")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+LogEntry", "Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAACHostel.Models.DataBaseModel+Student", "Student")
                        .WithOne("LogEntry")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+LogEntry", "Student_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAACHostel.Models.DataBaseModel+User", "User")
                        .WithOne("LogEntry")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+LogEntry", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hostel");

                    b.Navigation("Room");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Student", b =>
                {
                    b.HasOne("SAACHostel.Models.DataBaseModel+Faculty", "Faculty")
                        .WithOne("Student")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+Student", "Faculty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAACHostel.Models.DataBaseModel+Specialty", "Specialty")
                        .WithOne("Student")
                        .HasForeignKey("SAACHostel.Models.DataBaseModel+Student", "Specialty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Faculty", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Hostel", b =>
                {
                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Room", b =>
                {
                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Specialty", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+Student", b =>
                {
                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("SAACHostel.Models.DataBaseModel+User", b =>
                {
                    b.Navigation("Hostel");

                    b.Navigation("LogEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
